config/routes.rb
Rails.application.routes.draw do

	resources :posts, path: '/languages/:langName' do
		resources :comments
	end

	authenticate :user, lambda { |u| u.admin? } do
		begin
		  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
		rescue
		  redirect_to new_user_session_path
		end
	end
  	devise_for :users
	root to: 'home#index'
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	#'/'로 접속을 하면 home controller의 index action으로 작업을 하도록 만들어라.
	get '/login' => 'users#login'
	get '/free' => 'contents#free'
	get '/introduce' => 'contents#introduce'
	#method가 post방식임. /create url로 이동했을때 액션이 실행되도록, view에는 html파일이 없어도 되는 것.
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, :dependent => :destroy
    has_many :tags

    accepts_nested_attributes_for :tags, :allow_destroy => :true, :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
end

app/models/tag.rb
class Tag < ApplicationRecord
    belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
            :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :null_session
    def initialize()
        super()
        @languages = Language.all
        @APP_TITLE = "항개발"
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController    
    def create
        @lang = Language.find_by langName: params[:langName]
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        @comment.writer = current_user.email
        @comment.save()
        redirect_to post_path(@lang.langName, @post)
    end

    def destroy
        @lang = Language.find_by langName: params[:langName]
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@lang.langName, @post)
    end

    private
        def comment_params
            params.require(:comment).permit(:title, :body, :writer)
        end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
    def initialize()
        super()
    end

    def free
        @APP_TITLE += "-Free"
    end

    def introduce
        @APP_TITLE += "-Introduce"
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index #여기서 만든 index 메서드를 views에 home dir에 index파일을 만들면 이것과 연결이 됨. + route에도 연결을 시켜야함.	
		@APP_TITLE = @APP_TITLE + "-HOME"
	end	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def initialize()
    super()
  end
  # GET /posts
  # GET /posts.json
  def index
    @lang = Language.find_by langName: params[:langName]
    @posts = Post.where(:targetLanguage => @lang.langName)
    @APP_TITLE += "-CONTENTS(#{@lang.langName})"
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @lang = Language.find_by langName: params[:langName]
  end

  # GET /posts/new
  def new
    @lang = Language.find_by langName: params[:langName]
    @post = Post.new(:targetLanguage => @lang.langName, :writer => current_user.email)
  end

  # GET /posts/1/edit
  def edit
    @lang = Language.find_by langName: params[:langName]
  end

  # POST /posts
  # POST /posts.json
  def create
    @lang = Language.find_by langName: params[:langName]
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_path(@lang.langName,@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :writer, :like, :targetLanguage)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<p>
    <b>title:</b>
    <%= comment.title %>
</p>
<p>
    <b>body:</b>
    <%= comment.body %>
</p>
<p>
    <b>writer:</b>
    <%= comment.writer %>
</p>
<p>
    <%= link_to 'Destroy Comment', post_comment_path(@lang.langName, @post, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with( url: post_comments_path(@lang.langName, @post), model: [@post, @post.comments.build],  local: true) do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/contents/_postList.html.erb
<div id="post-body">
    <div class="d-flex flex-column">
        <%= form_tag "#", method: "get", class: "content-search input-group mx-0 mx-auto my-1", style: "width: 93%;" do%>
            <div class="input-group-prepend ">
                <div class="input-group-text bg-white border-right-0">
                    <i class="fas fa-search text-primary" aria-hidden="true"></i>
                </div>
            </div>
            <%= text_field_tag "inner-search", nil, placeholder: "Search in #{@lang.langName}", class: "search form-control border-left-0 pl-n3"%>
        <% end %>
        <% if current_user %>
            <%= link_to "글쓰기", "#", class: "btn btn-primary text-white mx-0 mx-auto my-1", style: "width: 93%;"%>
        <% end %>
        
        <div id="tags" class="mx-0 mx-auto overflow-auto">
            <%@testTag = ["#tag","#tagEx","#tagExample","#isittag?","#hah!"]%>
            <%for i in (0...100)%>
                <button class="btn btn-sm btn-outline-primary m-2" style="box-shadow: none;" data-toggle="button" aria-pressed="false">
                    <%=@testTag[Random.rand(0...@testTag.length())]%>
                </button>
            <%end%>
        </div>
        
    </div>
    <div id="post-list" class="p-3">
        <div class="row row-cols-1 justify-content-center w-100 m-0 m-auto">
            <% for i in (0...5)%>
                <%= link_to "#", class: "col card border-primary m-2 px-3" do%>
                    <div class="row">
                        <div class="col-3 col-md-2 m-0 m-auto" style="max-width: 8rem;">
                            <div id="like" class="border border-primary rounded text-primary text-center w-75 mx-0 mx-auto mb-4"><%=Random.rand(0...10)%><br><span>like</span></div>
                            <div id="answer-num" class="border border-primary rounded text-primary text-center w-75 mx-0 mx-auto mt-4"><%=Random.rand(0...10)%><br><span>answer</span></div>
                        </div>
                        <div id="post-content" class="col-9 col-md-10 card-body my-0 my-auto">
                            <div class="d-flex justify-content-between" >
                                <h3 id="post-title" class="card-title text-primary">title</h3>
                                <div id="post-user-info" class="text-primary">username</div>
                            </div>
                            <p id="post-primary" class="card-text overflow-hidden text-primary w-100" style="height: 3rem; text-overflow: ellipsis; white-space: nowrap;"> [content]<br>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam sollicitudin tempor id eu.</p>
                            <div id="post-tags" class="">
                                <% for i in (0...Random.rand(0...10)) %>
                                    <button class="btn btn-sm btn-primary text-white rounded-pill m-1">#tag</button>
                                <% end %>
                            </div>
                        </div>
                    </div>
                <% end %>
            <% end %>
        </div>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center mb-0 mt-4">
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Previous">
                        <span class="text-primary" aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li class="page-item"><a class="page-link text-primary" href="#">1</a></li>
                <li class="page-item"><a class="page-link text-primary" href="#">2</a></li>
                <li class="page-item"><a class="page-link text-primary" href="#">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Next">
                        <span class="text-primary" aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>

app/views/contents/free.html.erb
<!doctype html>
<html>
    <head>
        <%# stylesheet_link_tag "contents"%>
        <style>
            @media (min-width: 901px) { 
                
            }
            @media (max-width: 900.98px) {
                
            }
        </style>
    </head>
    <body>
        <h1>자유게시판</h1>
    </body>
</html>

app/views/contents/introduce.html.erb
<!doctype html>
<html>
    <head>
        <%= stylesheet_link_tag "introduce"%>
        <style>
            @media (min-width: 901px) { 
                
            }
            @media (max-width: 900.98px) {
                
            }
        </style>
    </head>
    <body>
        <div id="intro">
            <div id="intro-title" class="mt-5 text-center">
                <h3>OOO은 각종 버그에 지친<br>
                    항대생 여러분들을 환영합니다.
                </h3>
            </div>
            <div id="intro-content" class="mt-5 text-center">
                <h5>어디서 잘못됬는지도 모르겠고,<br>
                    에러 메시지를 봐도 모르겠고,<br>
                    검색해봐도 영어뿐...<br><br>
                    OOO은 <strong>한국어 개발 커뮤니티</strong>로<br>
                    편하게 질문하고, 빠르게 답을 받을 수 있습니다.
                </h5>
            </div>
            <div id="intro-team">
                <div class="team-title text-center">OOO 제작</div>
                    <ul class="team-members align-content-center text-center justify-content-center">
                        <li class="team-member">
                            <span class="member-name strong">최재혁</span><br>
                            <span class="member-posi">Team Leader<br>Designer<br>Back-end Developer</span>
                        </li>
                        <li class="team-member">
                            <span class="member-name strong">이준희</span><br>
                            <span class="member-posi"> Front-end Developer</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </body>
</html>

app/views/home/index.erb
<!DOCTYPE html>
<html>
	<head>
		<%= stylesheet_link_tag "home"%>
	</head>
	<body>
		<div class="jumbotron jumbotron-fluid mt-n1 bg-light text-dark">
			<p class="display-3 text-dark mx-0 mx-auto text-center">환영합니다</p>
			<p class="lead text-dark font-weight-bold text-center">항공대 학생들을 위한 개발 커뮤니티</p>
		</div>
		<div class="row row-cols-4 row-cols-sm-4 row-cols-md-6 card-column justify-content-center w-100 h-100 contents m-0 m-auto">
			<% @languages.each do |lang|%>
				<%= link_to "/languages/#{lang.langName}", class: "col card logo_img" do%>
					<%=image_tag "#{lang.extension}_logo.png", class: "card-img-top p-3"%>
					<div class="card-body">
						<h5 class="card-title"><%=lang.langName%></h5>
					</div>
				<% end %>
			<% end %>
		</div>
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%=@APP_TITLE%></title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
        <style>
            @media (min-width: 768px) { 
                .login-sm{display: none} .signin-sm{display:none}
                .login-lg{display: block} .signin-lg{display: block}
                .languages-map-sm{display: none} .languages-map-lg{display: block}
                .search-bar-sm{display: none} .search-bar-lg{display: flex}
            }
            @media (max-width: 767.98px) {
                .login-sm{display: block} .signin-sm{display:block}
                .login-lg{display: none} .signin-lg{display: none}
                .languages-map-sm{display: block} .languages-map-lg{display: none}
                .search-bar-sm{display: flex} .search-bar-lg{display: none}
            }
            <%= yield :mediaquery %>
        </style>
    </head>
    <body class="w-100 h-100 ">
        <!--<div class="alert alert-info alert-dismissible fade show m-0 fixed-top" role="alert">
            <%= notice %><br><%= alert %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>-->
		
        <header class="bg-primary">
            <nav class="navbar navbar-expand-md navbar-dark bg-primary">
                <a class="navbar-brand text-white" href="/">
                    <img class="mr-2" src=<%=asset_path "falcon_silhouette.png"%> width="35" height="35"/>항개발
                </a>
                
                <div class="d-flex ml-auto">
                    <button class="search-bar-sm btn btn-outline-light border-0 rounded-circle my-0 my-auto mr-2" type="button" data-toggle="collapse" data-target=".search-bar_collapse" aria-controls="search-bar_collapse" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-search text-light mx-n1" aria-hidden="true"></i>
                    </button>
                    <% if current_user %>
                        <%= link_to '로그아웃', destroy_user_session_path, method: :delete, class: "login-sm mr-1 align-self-center text-primary text-decoration-none btn btn-sm btn-light"%>
                    <% else %>
                        <%= link_to '로그인', new_user_session_path, class: "login-sm mr-1 align-self-center text-primary text-decoration-none btn btn-sm btn-light" %>
                        <%= link_to '회원가입', new_user_registration_path, class: "signin-sm mx-1 align-self-center text-primary text-decoration-none btn btn-sm btn-light" %>
                    <% end %>
                    
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse w-75" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="/introduce">소개</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="collapse" href="#languages-map">언어</a>
                            <div class="languages-map-sm collapse" id="languages-map">
                                <ul class="nav nav-pills justify-content-between bg-light px-3">
                                    <% @languages.each do |lang|%>
                                        <li class="nav-item">
                                            <%= link_to "#{lang.langName}", "/contents/#{lang.langName}", class: "nav-link text-primary"%>
                                        </li>
                                    <% end %>
                                </ul>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="/free">자유게시판</a>
                        </li>
                    </ul>
                </div>
                <div class="d-flex w-100 justify-content-end">
                    <%= form_tag "#", method: "get", class: "search-bar-lg form-inline input-group my-2 my-lg-0 w-50" do%>
                        <div class="input-group-prepend">
                            <div class="input-group-text bg-white border-right-0">
                                <i class="fas fa-search text-primary" aria-hidden="true"></i>
                            </div>
                        </div>
                        <%= text_field_tag "outter-search-lg", nil, placeholder: "Search", class: "search form-control mr-sm-2 border-left-0"%>
                    <% end %>
                    <% if current_user %>
                        <%= link_to '로그아웃', destroy_user_session_path, method: :delete, class: "login-lg mx-1 my-0 my-auto text-primary text-decoration-none btn btn-sm btn-light"%>
                    <% else %>
                        <%= link_to '로그인', new_user_session_path, class: "login-lg mx-1 my-0 my-auto text-primary text-decoration-none btn btn-sm btn-light"%>
                        <%= link_to '회원가입', new_user_registration_path, class: "signin-lg mx-1 my-0 my-auto align-self-center text-primary text-decoration-none btn btn-sm btn-light"%>
                    <% end %>
                </div>
                <%= form_tag "#", method: "get", class: "search-bar_collapse search-bar-sm collapse form-inline input-group my-2 my-lg-0 w-100" do%>
                    <div class="input-group-prepend">
                        <div class="input-group-text bg-white border-right-0">
                            <i class="fas fa-search text-primary" aria-hidden="true"></i>
                        </div>
                    </div>
                    <%= text_field_tag "outter-search-sm", nil, placeholder:"Search", class: "search form-control mr-sm-2 border-left-0"%>
                <% end %>
            </nav>

            <div class="languages-map-lg collapse bg-light border-bottom border-primary pl-5" id="languages-map">
                <ul class="nav">
                    <% @languages.each do |lang|%>
                        <li class="nav-item">
                            <%= link_to "#{lang.langName}", "/contents/#{lang.langName}", class: "nav-link text-primary"%>
                        </li>
                    <% end %>
                </ul>
            </div>
        </header>
        <%= yield :upperbody %>
        <%= yield %>

        <footer class='footer mt-5'>
            <div class='pt-4 pl-4 footer_font text-white'>항개발</div>
        </footer>
    </body>
</html>

app/views/posts/_questionList.html.erb
<div id="content-body">
    <div id="content-side" class="d-flex flex-column">
        <%= form_tag "#", method: "get", class: "content-search input-group mx-0 mx-auto my-1", style: "width: 93%;" do%>
            <div class="input-group-prepend ">
                <div class="input-group-text bg-white border-right-0">
                    <i class="fas fa-search text-primary" aria-hidden="true"></i>
                </div>
            </div>
            <%= text_field_tag "inner-search", nil, placeholder: "Search in #{@lang.langName}", class: "search form-control border-left-0 pl-n3"%>
        <% end %>
        <% if current_user %>
            <%= link_to "글쓰기", new_post_path, class: "btn btn-primary text-white mx-0 mx-auto my-1", style: "width: 93%;"%>
        <% end %>
        
        <div id="tags" class="mx-0 mx-auto overflow-auto">
            <%@testTag = ["#tag","#tagEx","#tagExample","#isittag?","#hah!"]%>
            <%for i in (0...100)%>
                <button class="btn btn-sm btn-outline-primary m-2" style="box-shadow: none;" data-toggle="button" aria-pressed="false">
                    <%=@testTag[Random.rand(0...@testTag.length())]%>
                </button>
            <%end%>
        </div>
    </div>
    <div id="post-list" class="p-3">
        <div class="row row-cols-1 justify-content-center w-100 m-0 m-auto">
            <% @posts.each do |post|%>
                <%= link_to post_path(@lang.langName,post.id), class: "col card border-primary m-2 px-3" do%>
                    <div class="row">
                        <div class="col-3 col-md-2 m-0 m-auto" style="max-width: 8rem;">
                            <div id="like" class="border border-primary rounded text-primary text-center w-75 mx-0 mx-auto mb-4"><%=post.like%><br><span>like</span></div>
                            <div id="answer-num" class="border border-primary rounded text-primary text-center w-75 mx-0 mx-auto mt-4"><%=post.comments.size%><br><span>answer</span></div>
                        </div>
                        <div id="post-content" class="col-9 col-md-10 card-body my-0 my-auto">
                            <div class="d-flex justify-content-between" >
                                <h3 id="post-title" class="card-title text-primary"><%=post.title%></h3>
                                <div id="post-user-info" class="text-primary"><%=post.writer%></div>
                            </div>
                            <p id="post-primary" class="card-text overflow-hidden text-primary w-100" style="height: 3rem; text-overflow: ellipsis; white-space: nowrap;"><%=post.body%></p>
                            <div id="post-tags" class="">
                                <% for i in (0...Random.rand(0...10)) %>
                                    <button class="btn btn-sm btn-primary text-white rounded-pill m-1">#tag</button>
                                <% end %>
                            </div>
                        </div>
                    </div>
                <% end %>
            <% end %>
            <!--<% for i in (0...5)%>
                <%= link_to "#", class: "col card border-primary m-2 px-3" do%>
                    <div class="row">
                        <div class="col-3 col-md-2 m-0 m-auto" style="max-width: 8rem;">
                            <div id="like" class="border border-primary rounded text-primary text-center w-75 mx-0 mx-auto mb-4"><%=Random.rand(0...10)%><br><span>like</span></div>
                            <div id="answer-num" class="border border-primary rounded text-primary text-center w-75 mx-0 mx-auto mt-4"><%=Random.rand(0...10)%><br><span>answer</span></div>
                        </div>
                        <div id="post-content" class="col-9 col-md-10 card-body my-0 my-auto">
                            <div class="d-flex justify-content-between" >
                                <h3 id="post-title" class="card-title text-primary">title</h3>
                                <div id="post-user-info" class="text-primary">username</div>
                            </div>
                            <p id="post-primary" class="card-text overflow-hidden text-primary w-100" style="height: 3rem; text-overflow: ellipsis; white-space: nowrap;"> [content]<br>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam sollicitudin tempor id eu.</p>
                            <div id="post-tags" class="">
                                <% for i in (0...Random.rand(0...10)) %>
                                    <button class="btn btn-sm btn-primary text-white rounded-pill m-1">#tag</button>
                                <% end %>
                            </div>
                        </div>
                    </div>
                <% end %>
            <% end %>-->
        </div>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center mb-0 mt-4">
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Previous">
                        <span class="text-primary" aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li class="page-item"><a class="page-link text-primary" href="#">1</a></li>
                <li class="page-item"><a class="page-link text-primary" href="#">2</a></li>
                <li class="page-item"><a class="page-link text-primary" href="#">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Next">
                        <span class="text-primary" aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', post_path(@lang.langName,@post) %> |
<%= link_to 'Back', post_path(@lang.langName,@post) %>

app/views/posts/index.html.erb
<%= stylesheet_link_tag "posts"%>

<div class="jumbotron jumbotron-fluid" id="descriptor">
    <p class="display-4 text-dark text-center">다양한 게시글에서 원하시는 정보를 찾아보세요.</p>
</div>
<ul class="nav nav-tabs m-1 " id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
        <a class="nav-link active text-primary" id="code-tab" data-toggle="tab" href="#code" role="tab" aria-controls="code" aria-selected="true">코드질문</a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link text-primary" id="study-tab" data-toggle="tab" href="#study" role="tab" aria-controls="study" aria-selected="false">공부방</a>
    </li>
    <li class="nav-item" role="presentation">
        <a class="nav-link text-primary" id="question-tab" data-toggle="tab" href="#question" role="tab" aria-controls="question" aria-selected="false">Q&A</a>
    </li>
</ul>
<div class="tab-content" id="primaryTabContents">
    <div class="tab-pane fade show active" id="code" role="tabpanel" aria-labelledby="code-tab">
        <%= render 'posts/questionList'%>
    </div>
    <div class="tab-pane fade" id="study" role="tabpanel" aria-labelledby="study-tab">
        ...제작중
    </div>
    <div class="tab-pane fade" id="question" role="tabpanel" aria-labelledby="question-tab">
        ...제작중
    </div>
</div>

<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Writer</th>
      <th>Tags</th>
      <th>Commentid</th>
      <th>Like</th>
      <th>Targetlanguage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.writer %></td>
        <td><%= post.like %></td>
        <td><%= post.targetLanguage %></td>
        <td><%= link_to 'Show', post_path(@lang.langName, post.id) %></td>
        <td><%= link_to 'Edit', edit_post_path(@lang.langName, post.id) %></td>
        <td><%= link_to 'Destroy', post_path(@lang.langName, post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path(@lang.langName) %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Writer:</strong>
  <%= @post.writer %>
</p>

<p>
  <strong>Like:</strong>
  <%= @post.like %>
</p>

<p>
  <strong>Targetlanguage:</strong>
  <% @post.targetLanguage %>
</p>

<p>
  <b>Tags:</b>
  <%= @post.tags.map { |t| t.name }.join(", ") %>
</p>

<h2>Comments</h2>
<%= render @post.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form" %>

<%= link_to 'Edit', edit_post_path(@lang.langName, @post) %> |
<%= link_to 'Back', posts_path(@lang.langName) %>

app/views/tags/_form.html.erb
<%= form.fields_for :tags do |tag_form| %>
  <div class="field">
    <%= tag_form.label :name, 'Tag:' %>
    <%= tag_form.text_field :name %>
  </div>
  <% unless tag_form.object.nil? || tag_form.object.new_record? %>
    <div class="field">
      <%= tag_form.label :_destroy, 'Remove:' %>
      <%= tag_form.check_box :_destroy %>
    </div>
  <% end %>
<% end %>